"""Regenerate benchmarks/real_outputs/README.md and the README benchmark table.

Reads each tool's report.json, extracts the summary block, and writes:
  - benchmarks/real_outputs/README.md
  - README.md real-output benchmark section

No numbers are hand-typed. Run after every benchmark re-run.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

TOOLS = [
    ("edison_trem2", "Edison Scientific Literature (TREM2)"),
    ("sakana_ai_scientist", "Sakana AI Scientist v2 (CompReg)"),
    ("answerthis_lactate", "AnswerThis (lactate ISF PK)"),
]

BASE = Path("benchmarks/real_outputs")
ROOT = Path(__file__).parent.parent
TODAY = "2026-05-06"


def _load(slug: str) -> dict[str, float]:
    data: dict[str, dict[str, float]] = json.loads(
        (BASE / slug / "report.json").read_text(encoding="utf-8")
    )
    return data["summary"]


def _pct(rate: float) -> str:
    return f"{rate * 100:.1f}%"


def _cost(usd: float) -> str:
    return f"${usd:.2f}"


def _make_row(label: str, s: dict[str, float]) -> str:
    return (
        f"| {label}"
        f" | {s['total_claims']}"
        f" | {s['supported']}"
        f" | {s['partially_supported']}"
        f" | {s['unsupported']}"
        f" | {s['not_addressed']}"
        f" | {_pct(s['citation_found_rate'])}"
        f" | {s['fulltext_verified']}"
        f" | {s['retracted_sources']}"
        f" | {s['numeric_checks_run']}"
        f" | {s['numeric_inconsistencies_flagged']}"
        f" | {_cost(s['total_cost_usd'])} |"
    )


HEADER = (
    "| tool | claims | supported | partially_supported | unsupported | not_addressed"
    " | citation_found_rate | fulltext_verified | retracted_sources"
    " | numeric_checks_run | numeric_inconsistencies_flagged | cost |"
)
SEP = "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"


def build_table() -> tuple[str, dict[str, float]]:
    summaries = [(label, _load(slug)) for slug, label in TOOLS]
    totals: dict[str, float] = {
        k: 0.0
        for k in [
            "total_claims",
            "supported",
            "partially_supported",
            "unsupported",
            "not_addressed",
            "fulltext_verified",
            "retracted_sources",
            "numeric_checks_run",
            "numeric_inconsistencies_flagged",
            "total_cost_usd",
        ]
    }
    for _, s in summaries:
        for k in totals:
            totals[k] += s.get(k, 0)

    total_claims = int(totals["total_claims"])
    weighted_cfr = (
        sum(_load(slug)["citation_found_rate"] * _load(slug)["total_claims"] for slug, _ in TOOLS)
        / total_claims
        if total_claims
        else 0.0
    )

    total_row = (
        f"| **Total**"
        f" | **{int(totals['total_claims'])}**"
        f" | **{int(totals['supported'])}**"
        f" | **{int(totals['partially_supported'])}**"
        f" | **{int(totals['unsupported'])}**"
        f" | **{int(totals['not_addressed'])}**"
        f" | **{_pct(weighted_cfr)}**"
        f" | **{int(totals['fulltext_verified'])}**"
        f" | **{int(totals['retracted_sources'])}**"
        f" | **{int(totals['numeric_checks_run'])}**"
        f" | **{int(totals['numeric_inconsistencies_flagged'])}**"
        f" | **{_cost(totals['total_cost_usd'])}** |"
    )

    data_rows = "\n".join(_make_row(label, s) for label, s in summaries)
    table = f"{HEADER}\n{SEP}\n{data_rows}\n{total_row}"
    return table, dict(totals)


def write_summary(table: str) -> None:
    canary_s = json.loads((BASE.parent / "canary" / "report.json").read_text(encoding="utf-8"))[
        "summary"
    ]
    canary_row = _make_row("Canary suite", canary_s)

    content = f"""# Real-Tool Benchmark Summary

Aggregate verification outcomes across three distinct AI-for-science tools. Numbers are programmatically extracted from each `report.json`'s `summary` block — no hand-typing. Generated by `python scripts/generate_summary.py`. Re-run after each benchmark run.

Pipeline: Phase 1 (full-text, BM25 token-aware passage selection) + Phase 2 (numeric checks: OR/CI + p-value/CI).

{table}

### Canary (seeded controls — not real-tool evidence)

{HEADER}
{SEP}
{canary_row}

The canary is a controlled four-claim input designed to exercise contradiction detection, retraction flagging, numeric inconsistency, and weak-resolution diagnostics. Its results are not pooled with the real-tool aggregate above.

## Reading the table

- **claims**: total verifiable claims extracted from the input
- **supported / partially_supported / unsupported / not_addressed**: full-text verification verdicts
- **citation_found_rate**: fraction of claims where the cited source was resolved (title-match ≥ 15%)
- **fulltext_verified**: claims that received full-text BM25 passage selection and verification
- **retracted_sources**: cited papers flagged as retracted via CrossRef `update-to`
- **numeric_checks_run**: claims whose extracted assertions formed an OR/CI or p-value/CI tuple
- **numeric_inconsistencies_flagged**: subset of `numeric_checks_run` where the deterministic check failed
- **cost**: total Anthropic API spend (claude-sonnet-4-6, prompt-cached system prompts)
"""
    out = BASE / "README.md"
    out.write_text(content, encoding="utf-8")
    print(f"[summary] written -> {out}")


def update_readme(table: str) -> None:
    readme = ROOT / "README.md"
    text = readme.read_text(encoding="utf-8")

    # Replace the benchmark section: from "## Real-Output Benchmark" through the
    # blank line that follows the table + interpretation paragraph.
    new_section = (
        "## Real-Output Benchmark\n\n"
        "Committed reports under `benchmarks/real_outputs/` currently cover three\n"
        "AI-for-science outputs:\n\n"
        f"{table}\n\n"
        f"Numbers regenerated {TODAY} from `benchmarks/real_outputs/README.md`. "
        "Re-run via `python scripts/check_summary_alignment.py`.\n"
    )

    pattern = r"## Real-Output Benchmark\b.*?(?=\n## |\Z)"
    updated = re.sub(pattern, new_section.rstrip() + "\n", text, flags=re.DOTALL)
    if updated == text:
        print("[readme] WARNING: benchmark section not found or unchanged")
    else:
        readme.write_text(updated, encoding="utf-8")
        print(f"[readme] updated -> {readme}")


def main() -> None:
    table, totals = build_table()
    write_summary(table)
    update_readme(table)
    print(
        f"  totals: {int(totals['total_claims'])} claims, "
        f"{int(totals['supported'])} supported, "
        f"{int(totals['partially_supported'])} partial, "
        f"{int(totals['unsupported'])} unsupported, "
        f"{int(totals['not_addressed'])} not_addressed, "
        f"${totals['total_cost_usd']:.2f} total cost"
    )


if __name__ == "__main__":
    main()
