"""Report generation — aggregates pipeline results and writes report.json + provenance.jsonl."""

from __future__ import annotations

import dataclasses
import hashlib
import json
import time
import uuid
from pathlib import Path

import structlog

from src.models import Claim, ProvenanceStep, ResolvedSource, VerificationResult

logger: structlog.BoundLogger = structlog.get_logger(__name__)

# Cost rates for claude-sonnet-4-6 (USD per token)
_COST_INPUT_PER_TOKEN = 3.0 / 1_000_000
_COST_INPUT_CACHED_PER_TOKEN = 0.30 / 1_000_000
_COST_OUTPUT_PER_TOKEN = 15.0 / 1_000_000


def _hash(data: str) -> str:
    return hashlib.sha256(data.encode()).hexdigest()


def _compute_cost(steps: list[ProvenanceStep]) -> float:
    total = 0.0
    for step in steps:
        if step.tokens_in is not None:
            # cache_hit=None (short-circuit steps) treated as uncached — conservative estimate
            rate = _COST_INPUT_CACHED_PER_TOKEN if step.cache_hit else _COST_INPUT_PER_TOKEN
            total += step.tokens_in * rate
        if step.tokens_out is not None:
            total += step.tokens_out * _COST_OUTPUT_PER_TOKEN
    return total


def _compute_summary_stats(
    claims: list[Claim],
    results: dict[str, VerificationResult],
    sources: dict[str, ResolvedSource],
) -> dict[str, int | float]:
    """Pure helper — compute summary statistics. No I/O."""
    total = len(claims)
    supported = sum(
        1
        for c in claims
        if results.get(c.claim_id, VerificationResult("not_addressed", "", 0.0)).status
        == "supported"
    )
    unsupported = sum(
        1
        for c in claims
        if results.get(c.claim_id, VerificationResult("not_addressed", "", 0.0)).status
        == "unsupported"
    )
    not_addressed = sum(
        1
        for c in claims
        if results.get(c.claim_id, VerificationResult("not_addressed", "", 0.0)).status
        == "not_addressed"
    )
    partially_supported = sum(
        1
        for c in claims
        if results.get(c.claim_id, VerificationResult("not_addressed", "", 0.0)).status
        == "partially_supported"
    )

    found_count = sum(
        1
        for c in claims
        if sources.get(c.claim_id, ResolvedSource(False, None, None, None, None)).found
    )
    citation_found_rate = found_count / total if total > 0 else 0.0

    return {
        "total_claims": total,
        "supported": supported,
        "unsupported": unsupported,
        "not_addressed": not_addressed,
        "partially_supported": partially_supported,
        "citation_found_rate": citation_found_rate,
    }


def build_report(
    report_id: str,
    input_text: str,
    claims: list[Claim],
    sources: dict[str, ResolvedSource],
    results: dict[str, VerificationResult],
    provenance_steps: list[ProvenanceStep],
    *,
    output_dir: Path | None = None,
) -> Path:
    """Aggregate pipeline results and write report.json + provenance.jsonl.

    report_id must be generated by the caller (pipeline entry point), not here.
    Creates reports/runs/{report_id}/ with mkdir(parents=True, exist_ok=True).
    output_dir defaults to project_root/reports/.
    Empty claims list produces valid report with total_claims=0.
    Returns path to the run directory (reports/runs/{report_id}/).
    Side effects: creates two files. No other side effects.
    """
    resolved_output_dir = output_dir if output_dir is not None else _default_output_dir()
    run_dir = resolved_output_dir / "runs" / report_id
    run_dir.mkdir(parents=True, exist_ok=True)

    stats = _compute_summary_stats(claims, results, sources)
    total_cost = _compute_cost(provenance_steps)
    stats["total_cost_usd"] = total_cost

    claim_records = []
    for claim in claims:
        source = sources.get(
            claim.claim_id,
            ResolvedSource(found=False, doi=None, title=None, abstract=None, similarity_score=None),
        )
        result = results.get(
            claim.claim_id,
            VerificationResult(status="not_addressed", explanation="No result.", confidence=0.0),
        )
        claim_records.append(
            {
                "claim_id": claim.claim_id,
                "claim_text": claim.claim_text,
                "claim_type": claim.claim_type,
                "cited_authors": claim.cited_authors,
                "cited_year": claim.cited_year,
                "source": dataclasses.asdict(source),
                "verification": dataclasses.asdict(result),
            }
        )

    report = {
        "report_id": report_id,
        "timestamp": time.time(),
        "input_text": input_text,
        "summary": stats,
        "claims": claim_records,
    }

    with open(run_dir / "report.json", "w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    # Build aggregate provenance step.
    # claim_id=report_id by convention: aggregate step belongs to the run, not a single claim.
    claim_ids = [c.claim_id for c in claims]
    aggregate_step = ProvenanceStep(
        step_id=str(uuid.uuid4()),
        claim_id=report_id,
        operation="aggregate",
        input_hash=_hash(repr(claim_ids)),
        output_hash=_hash(repr(stats)),
        model_id=None,
        timestamp=time.time(),
        tokens_in=None,
        tokens_out=None,
        cache_hit=None,
        confidence=None,
    )

    all_steps = [*provenance_steps, aggregate_step]

    with open(run_dir / "provenance.jsonl", "w", encoding="utf-8") as f:
        for step in all_steps:
            f.write(json.dumps(dataclasses.asdict(step)) + "\n")

    logger.info(
        "report_written",
        report_id=report_id,
        total_claims=stats["total_claims"],
        total_cost_usd=total_cost,
        run_dir=str(run_dir),
    )

    return run_dir


def _default_output_dir() -> Path:
    """Return default output directory: <project_root>/reports/."""
    return Path(__file__).parent.parent / "reports"
